apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
spec:
  serviceAccountName: workflows-user
  templates:
  - name: hello
    container:
      image: alpine
      command: [echo]
      args: ["hello world"]
      resources:
        limits:
          memory: 32Mi
          cpu: 100m
